"""Add token fields to Клиент

Revision ID: 4727f469dd09
Revises: 8a7c2ae8a99d
Create Date: 2025-04-30 11:41:03.928269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4727f469dd09'
down_revision: Union[str, None] = '8a7c2ae8a99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('клиент', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('клиент', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('клиент', sa.Column('access_expiration', sa.DateTime(), nullable=True))
    op.add_column('клиент', sa.Column('refresh_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('клиент', 'refresh_expiration')
    op.drop_column('клиент', 'access_expiration')
    op.drop_column('клиент', 'refresh_token')
    op.drop_column('клиент', 'access_token')
    # ### end Alembic commands ###
