"""Add access/refresh tokens to client without expiration

Revision ID: 581348ed14a9
Revises: 4727f469dd09
Create Date: 2025-04-30 12:07:59.599510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581348ed14a9'
down_revision: Union[str, None] = '4727f469dd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('клиент', 'access_expiration')
    op.drop_column('клиент', 'refresh_expiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('клиент', sa.Column('refresh_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('клиент', sa.Column('access_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
