"""Add cryptography to balance invest_account

Revision ID: 5f3c67611350
Revises: 2e6eec644517
Create Date: 2025-05-06 13:48:09.305450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.crud import EncryptedBalance


revision: str = '5f3c67611350'
down_revision: Union[str, None] = '2e6eec644517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('инвестиции', sa.Column('новый_баланс', EncryptedBalance, nullable=True))

    op.drop_column('инвестиции', 'баланс')

    op.alter_column('инвестиции', 'новый_баланс', new_column_name='баланс')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('инвестиции', sa.Column('старый_баланс', sa.Float, nullable=True))
    op.drop_column('инвестиции', 'баланс')
    op.alter_column('инвестиции', 'старый_баланс', new_column_name='баланс')
    # ### end Alembic commands ###
