"""Добавлено поле дата_операции в таблицу банковская_операция

Revision ID: 842ea5e46b97
Revises: 146c2ad1d672
Create Date: 2025-05-13 11:08:52.733296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842ea5e46b97'
down_revision: Union[str, None] = '146c2ad1d672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('банковская_операция', sa.Column('дата_операции', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('банковская_операция', 'дата_операции')
    # ### end Alembic commands ###
