"""Change телефон to пароль

Revision ID: 8a7c2ae8a99d
Revises: cbaa7fd4e8ab
Create Date: 2025-04-16 13:31:15.815427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7c2ae8a99d'
down_revision: Union[str, None] = 'cbaa7fd4e8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('клиент', sa.Column('пароль', sa.String(), nullable=True))
    op.create_index(op.f('ix_клиент_email'), 'клиент', ['email'], unique=True)
    op.create_index(op.f('ix_клиент_id_клиента'), 'клиент', ['id_клиента'], unique=False)
    op.drop_column('клиент', 'телефон')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('клиент', sa.Column('телефон', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_клиент_id_клиента'), table_name='клиент')
    op.drop_index(op.f('ix_клиент_email'), table_name='клиент')
    op.drop_column('клиент', 'пароль')
    # ### end Alembic commands ###
